name: pyg-env
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - scipy
  - scikit-learn
  - ipython
  - ipykernel
  - jupyter
  - pytorch
  - torchvision
  - torchaudio
  - pip
  - pip:
      - torch-geometric
      - pyg-lib
      - torch-scatter
      - torch-sparse
      - torch-cluster
      - torch-spline-conv
      - imbalanced-learn
      - shap
      - opencv-python-headless
      - music21
      - partitura
      - xmlschema
